[package]
name        = "flihtmx"
description = "A web-based todo application built with Flix and HTMX that demonstrates effect-oriented programming principles"
version     = "0.1.0"
flix        = "0.64.0"
authors     = ["Valentin Erokhin <valentin.erokhin@s.wu.ac.at>"]
